### ISSUE TITLE
Precompiled assets loaded from `tmp/rails_lineman` in Dev

### ISSUE THREAD

**Issue by searls** [linemanjs/rails-lineman#7]
After precompiling, it seems `tmp/rails_lineman` is serving out those assets (in the same way public/assets would). I had to delete the directory to see new changes.

**Comment by rjo1970** [comment]
Hmm, yeah.  I see it:

``` ruby
Rails.root.join(File.join("tmp", "rails_lineman", "lineman"))
```

Should everything be dumped to public/assets, instead?

**Comment by searls** [comment]
I suppose. I hate that behavior in rails itself (in Dev mode). But it'd be more consistent

**Comment by searls** [comment]
Can you recall what your reasoning was for this block @rjo1970?

```

    def destination
      if is_precompilable?
        Rails.root.join(File.join("tmp", "rails_lineman", "lineman"))
      else
        Rails.root.join(File.join("public", "assets", @descriptor))
      end
    end
```

I don't remember/understand that and I'm wary of nixing it until I know what you were thinking in 85e0be91

**Comment by searls** [comment]
Alright the further down the rabbit hole I get, the more confused I am. What's the point of the configuration property `remove_lineman_assets_after_asset_pipeline_precompilation`? Why would someone want to remove fonts & images right after they precompile?

**Comment by rjo1970** [comment]
Probably of no use now, but that was simply an extracted method I formed
from the existing code before I touched it.

I am thinking (not looking at your updated release) you would have wanted a
single Rails.root.join on assets only, and have the lineman assets get
poured into there directly.
